### ISSUE TITLE
cond fallthrough doesn't print (useful) line number

### ISSUE THREAD

**Issue by shriram** [mflatt/plait#12]
If you write just `(cond)` in the definitions window, you get a fallthrough error but with no highlighting at all. If you either write it in the REPL or invoke it from there — e.g., put `(define (f) (cond))` in definitions and call `(f)` from the REPL — you get the following:
```
Library/Racket/7.8/pkgs/plait/main.rkt:1377:38: cond: no matching clause
```

**Comment by shriram** [comment]
I notice that in`main.rkt`, replacing
```
                             #'([else (cond-error)])))]
```
with
```
                             (datum->syntax stx
                                            '([else (cond-error)]))
```
helps with highlighting the entire `cond` clause for errors in the definitions window (while loading definitions), but it doesn't make a difference to errors in or induced from the REPL.

**Comment by mflatt** [comment]
Thanks! I'll push a variant of that repair.
