### ISSUE TITLE
Plait license

### ISSUE THREAD

**Issue by lassik** [mflatt/plait#17]
Hi. We've recently been exploring a statically typed variant of Scheme with full type inference. Plait is very nice code along these lines. Is it available under an open source license, and could we adapt some of it for prototyping?

We're not working full-time and are dealing with a lot of unresolved design questions so it'll take like a year before we can ship anything remotely usable. We're starting from a foundation where the language is lacking an `any` type, which is different from Typed Racket, Typed Clojure, Common Lisp, TypeScript, and the Python/Ruby typing add-ons.

Does Racket have any plans in this direction, or are you going forward with Typed Racket?

**Comment by mflatt** [comment]
Hi — you're welcome to use the code. I've add the missing `LICENSE` file to put the the code is under the MIT license.

I doubt that Racket itself will be moving in this direction. Plait was designed for teaching, and it has limitations (especially for interoperability) that Typed Racket addresses far better. Typed Racket is definitely more in the future of Racket than Plait.

**Comment by lassik** [comment]
Thank you very much! We'll make sure to credit you, and all of our code will naturally be open source as well.

Part of the reason we started the project is to consciously go in a different direction than seemingly all other dynamic languages. We have some ideas for interop but have not yet tried them out for real so it may turn out to be a bad bet. Time will tell!
