### ISSUE TITLE
Properly support `or` and `and` in #:lazy dialect

### ISSUE THREAD

**Issue by kimmyg** [mflatt/plait#18]
In `#lang plait #:lazy`, `(or (zero? 1) (zero? 0))` produces `#f`.

The issue appears to be that the expansion of `or` doesn't consider `delay`ed values: `(delay (zero? 1))` evaluates to a non-`#f` value but, when forced, produces `#f`.

A similar issue exists with `and`.

The implementation wraps the `racket/base` `or` and `and`. If the fix is straightforward, such as using the `lazy` equivalents or implementing them inline, I'm happy to create a pull request.

**Comment by mflatt** [comment]
Thanks for the report! And sorry for the delay — I must have missed it at the time.

**Comment by kimmyg** [comment]
The delay is no problem. Thank you!
