### ISSUE TITLE
problem printing recursive structures

### ISSUE THREAD

**Issue by bremner** [mflatt/plait#2]
Thanks for writing plait. I appreciate the improvements over plai-typed (even if it means reverting some of my classroom code back to before I converted it to plai-typed from eli's typed/racket dialect),

I had a nasty and tricky to debug surprise with one trivial conversion from plai-typed (just editing the type-case syntax). As detailed below, the printer seems to hang on recursive structures, but not in the repl.
  
``` racket
#lang plait

(define-type Hat
  [empty-hat]
  [hat (bunny : Rabbit)])

(define-type Rabbit
  [rabbit  [hat : (Boxof Hat)]])

(define (looper)
  (let*
      ([the-box (box (empty-hat))]
       [the-rabbit (rabbit the-box)]
       [the-hat (hat the-rabbit)])
    (begin
      (set-box! the-box the-hat)
      the-hat)))

;; 1) calling looper in the repl works

;; 2) this works, and thumper can be evaluated in the REPL
(define thumper (looper))

;; this hangs
;(looper)

;; so does this
thumper
``` 

I'm running Racket 7.1 (regular, not on chez). I tested in DrRacket and racket-mode in emacs. I'm using plait commit 15396db448f09f8f813

**Comment by mflatt** [comment]
Thanks for the report!
