### ISSUE TITLE
recursive tuple type

### ISSUE THREAD

**Issue by LuKuangChen** [mflatt/plait#22]
The follow program attempts to define a function that returns a stream of numbers, similar to `(in-naturals n)`.

```racket
#lang plait

(define (f n)
  (values n (λ () (f (+ 1 n)))))
```

I expect this program to be rejected however, it runs. And the type of `f` seems to be wrong.

```racket
> f
- (Number -> (Number * (-> (Number * (-> 'a)))))
#<procedure:f>
>
```

Note that plait definitely can detect recursive types in simpler contexts:

```racket
> ((lambda (f) (f f)) (lambda (f) (f f)))
typecheck failed: cycle in type constraints type mismatch: '_a vs. ('_a -> '_b)
```

Kuang-Chen Lu & Paul Biberstein

**Comment by mflatt** [comment]
Thanks for the report! This certainly looks like a problem with the type checker, and I'll investigate.
