### ISSUE TITLE
provide some type predicates?

### ISSUE THREAD

**Issue by bremner** [mflatt/plait#3]
I have some examples that only really work as dynamically typed (or occurence typed) racket. On the other hand I would like to use the same syntax as the other examples as much as possible, in particular using type-case.  "#lang plait #:untyped" gets me part of the way there, but I'm missing predicates like procedure?, number?, and string?.  Would it be possible/sensible to provide those (perhaps only in #:untyped).

**Comment by mflatt** [comment]
I'm reluctant to add predicates like that. Would it work for your purposes to `require` them?

```
(require (typed-in racket/base
                   [number? : ('a -> Boolean)]))
```

**Comment by bremner** [comment]
Matthew Flatt <notifications@github.com> writes:

> I'm reluctant to add predicates like that. Would it work for your purposes to `require` them?
>
> ```
> (require (typed-in racket/base
>                    [number? : ('a -> Boolean)]))
> ```

Oh! That's fine. I misunderstood how require worked in plait. Indeed
it's already documented, so feel free to close the issue.

Sorry for not reading the docs,

d

**Comment by mflatt** [comment]
Ok - good!
