### ISSUE TITLE
types not exported from plait modules.

### ISSUE THREAD

**Issue by bremner** [mflatt/plait#5]
I'm trying to structure an assignment so that the students do most of the work in the typed world, but then for some part where that doesn't work use a separate module with 
```racket
(module untyped-part plait
  #:untyped
  (require (submod ".." parts-one-and-two))

)
```
That mostly works with explicit requires (as an aside, I think what I'm trying to do here is simulate an untyped module+). The blocker at this point is that the types defined by define-type are not visible in the module `untyped-part`.  I'm not sure if this is by design, or if it is a bug. In either case I'm curious about workarounds or alternative approaches to the underlying issue.  

For context I'm trying to work through an example where the evaluator for some toy language returns racket numbers/procedures. This was originally written in Eli's typed/racket dialect which supports union-types.

**Comment by mflatt** [comment]
I'm not immediately sure why you'd need to refer to a type in `untyped-part`. Is it for `type-case`?

**Comment by bremner** [comment]
Matthew Flatt <notifications@github.com> writes:

> I'm not immediately sure why you'd need to refer to a type in `untyped-part`. Is it for `type-case`?
>

Yes, I want to have two different evaluators that take an AST defined
with the same define-type

**Comment by mflatt** [comment]
That makes sense. It's not a simple fix, but I will look into it more in the next day or two.

**Comment by mflatt** [comment]
Should work now — but please confirm, and we'll reopen if I did not get it right for your case.

**Comment by bremner** [comment]
Matthew Flatt <notifications@github.com> writes:

> Should work now — but please confirm, and we'll reopen if I did not get it right for your case.
>
> -- 

Thanks! It seems to work fine.
