### ISSUE TITLE
type-case doesn't allow a type alias to a structured type with variants :(

### ISSUE THREAD

**Issue by ProfessorO** [mflatt/plait#7]
```
(define-type Type
  (variant))
(define-type-alias Alias Type)
(type-case Alias (variant1)
  [(variant) ""])
```

results in:
` type-case: this must be a type defined with define-type in: Alias`

Isn't a type alias supposed to be usable anywhere the aliased type would be used?

**Comment by mflatt** [comment]
Yes. It's a pain to support aliases in `type-case`, so I never got around to it before, but I'll do that now.
