### ISSUE TITLE
s-exp-match? function does not accept all forms of s-expressions

### ISSUE THREAD

**Issue by dakotacookenmaster** [mflatt/plait#8]
In the console, the following S-Expressions are valid in the s-exp-match? function:
```
> `true
- S-Exp
> (s-exp-match? `true `true)
- Boolean
#t 
```
However, the following S-Expressions are NOT valid in the same function:
```
> `#t    ;  `#t is indeed an S-Expression
- S-Exp
> (s-exp-match? `#t `#t)
- Boolean
. . s-exp-match?: bad pattern: `#t
```
Is this the intended behavior, or a bug?

**Comment by mflatt** [comment]
I agree that it would be better for any S-expression to work as a pattern, so I'll extend `s-exp-match?`.

**Comment by ProfessorO** [comment]
Possibly related: it would be nice to have ``` `BOOLEAN``` match Boolean values in the s-exp-match? patterns. That would complete the collection of built-in-types that can easily be matched.
```
> (s-exp-match? `BOOLEAN `#t)
- Boolean
#f
```
Should return #t instead.
